/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package software_project.GUI;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import software_project.Controller.OldCustomerController;
import software_project.Model.GetBillsOfSpecificMeterCode;
/**
 *
 * @author HP
 */
public class OldCustomerOptions extends javax.swing.JFrame {

    public long metercode ;
    public OldCustomerOptions(long metercode) {
        initComponents();
        this.metercode = metercode ;
    }
    

    private OldCustomerOptions() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();
        Bills = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Complain = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        PayBills = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Reading = new javax.swing.JButton();
        Leave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("show bills");

        Bills.setText("Bills");
        Bills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillsActionPerformed(evt);
            }
        });

        jLabel2.setText("make complain");

        Complain.setText("complain");
        Complain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComplainActionPerformed(evt);
            }
        });

        jLabel3.setText("pay bill");

        PayBills.setText("Pay");
        PayBills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayBillsActionPerformed(evt);
            }
        });

        jLabel4.setText("enter reading");

        Reading.setText("reading");
        Reading.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadingActionPerformed(evt);
            }
        });

        Leave.setText("leave");
        Leave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(Leave, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(Complain)
                    .addComponent(Bills)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Reading)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(PayBills)))
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bills)
                    .addComponent(PayBills))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Reading)
                    .addComponent(Complain))
                .addGap(105, 105, 105)
                .addComponent(Leave)
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillsActionPerformed
        if(evt.getSource() == Bills)
        {
            try {
                OldCustomerShowBillsView c1 = new OldCustomerShowBillsView(metercode) ;
                c1.show();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(OldCustomerOptions.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(OldCustomerOptions.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_BillsActionPerformed

    private void ComplainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComplainActionPerformed
        if(evt.getSource() == Complain)
        {
            OldCustomerComplainView c1 = new OldCustomerComplainView(metercode) ;
            c1.show() ;
        }
    }//GEN-LAST:event_ComplainActionPerformed

    private void LeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeaveActionPerformed
        this.dispose();
    }//GEN-LAST:event_LeaveActionPerformed

    private void ReadingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadingActionPerformed
        if(evt.getSource() == Reading)
        {
            OldCustomerReadingView c1 = new OldCustomerReadingView(metercode) ;
            c1.show() ;
        }
    }//GEN-LAST:event_ReadingActionPerformed

    private void PayBillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayBillsActionPerformed
        try {
            ArrayList <GetBillsOfSpecificMeterCode> BillList = new ArrayList() ;
            OldCustomerController c1 = new OldCustomerController() ;
            BillList = c1.BillsOfSpecificMeterCodeController(metercode);
            if(BillList.size() == 0)
            {
                JOptionPane.showMessageDialog(this, "this account does not has unpaid bills");
            }
            else
            {
                OldCustomerPayBillView c2 = new OldCustomerPayBillView(metercode) ;
                c2.show();
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OldCustomerOptions.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(OldCustomerOptions.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PayBillsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OldCustomerOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OldCustomerOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OldCustomerOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OldCustomerOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OldCustomerOptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bills;
    private javax.swing.JButton Complain;
    private javax.swing.JButton Leave;
    private javax.swing.JButton PayBills;
    private javax.swing.JButton Reading;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
