package software_project.GUI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class UpdateUserChoiceView extends javax.swing.JFrame {

    /**
     * Creates new form UpdateUserChoice
     */
    public UpdateUserChoiceView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateCustomer = new javax.swing.JButton();
        updateOperator = new javax.swing.JButton();
        updateAdministrator = new javax.swing.JButton();
        backToAdminChoice = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        updateCustomer.setText("Update Coustomer");
        updateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCustomerActionPerformed(evt);
            }
        });

        updateOperator.setText("Update Operator");
        updateOperator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateOperatorActionPerformed(evt);
            }
        });

        updateAdministrator.setText("Update Administrator");
        updateAdministrator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAdministratorActionPerformed(evt);
            }
        });

        backToAdminChoice.setText("Back");
        backToAdminChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToAdminChoiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(updateAdministrator)
                            .addComponent(updateOperator, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(backToAdminChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(updateCustomer)
                .addGap(31, 31, 31)
                .addComponent(updateOperator)
                .addGap(36, 36, 36)
                .addComponent(updateAdministrator)
                .addGap(33, 33, 33)
                .addComponent(backToAdminChoice)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCustomerActionPerformed
        UpdateCustomerView updateCustomer = new UpdateCustomerView();
        updateCustomer.setLocation(400, 200);
        updateCustomer.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_updateCustomerActionPerformed

    private void updateOperatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateOperatorActionPerformed
        UpdateOperatorView updateOperator = new UpdateOperatorView();
        updateOperator.setLocation(400, 200);
        updateOperator.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_updateOperatorActionPerformed

    private void updateAdministratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAdministratorActionPerformed
        UpdateAdministratorView updateAdministrator = new UpdateAdministratorView();
        updateAdministrator.setLocation(400, 200);
        updateAdministrator.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_updateAdministratorActionPerformed

    private void backToAdminChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToAdminChoiceActionPerformed
        AdminChoice adminChoice = new AdminChoice();
        adminChoice.setLocation(400, 200);
        adminChoice.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backToAdminChoiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateUserChoiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateUserChoiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateUserChoiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateUserChoiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateUserChoiceView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToAdminChoice;
    private javax.swing.JButton updateAdministrator;
    private javax.swing.JButton updateCustomer;
    private javax.swing.JButton updateOperator;
    // End of variables declaration//GEN-END:variables
}
